### ISSUE TITLE
raise MeshplexError("Degenerate cells.")

### ISSUE THREAD

**Issue by rob-rb** [nschloe/optimesh#71] opened 2021-02-09 20:31 UTC
Dear Nico,

I really appreciate your work a lot.
I had to adapt the main.py for my workflow. 
I have one geometry where the workflow now works great (it is for a schwarz-p-surface).
now I try to get it work for other minimal surfaces. I have the issue that once in a while the delaunay_flip_code is raising the expection above.

I tried the following fix
```python
mesh.points = new_points
n = len(mesh.cells["points"])
dels = numpy.array(range(n))[mesh.cell_volumes < 1e-2]
mesh.remove_cells(dels)
mesh.flip_until_delaunay()
```
it removes some cells but the error persists. Could you give me a hint what went wrong?

It's funny actually you write in the readme:

> only works for triangular meshes, flat and on a surface

but for me your library seems to work as well for 3d-coords without a surface (Actually the surface it "should" converge to is uknown beforehand)

**Comment by rob-rb** [comment] 2021-02-09 20:46
funny enough printing the mesh.cell_volumes i get:
0.0003894926208074324 as a minimum before the breakdown happens. It seems tria_areas in mesh_plex and cell_volumes are not the same.

**Comment by rob-rb** [comment] 2021-02-09 21:04
It's funny actually you write in the readme:

> only works for triangular meshes, flat and on a surface

but for me your library seems to work as well for 3d-coords without a surface (Actually the surface it "should" converge to is uknown beforehand)

**Comment by rob-rb** [comment] 2021-02-09 21:52
yep I tried to reduce max_step when getting this error. The problem copying the mesh by
```

def copy_mesh(mesh):
    return meshplex.MeshTri(np.array(mesh.points, copy=True), np.array(mesh.cells["points"], copy=True))
```

leads to the error:

> /opt/conda/lib/python3.8/site-packages/meshplex/mesh_tri.py in create_edges(self)
>     508         a_unique, inv, cts = unique_rows(a)
>     509 
> --> 510         assert np.all(cts < 3), "No edge has more than 2 cells. Are cells listed twice?"
>     511 
>     512         self._is_boundary_edge_local = (cts[inv] == 1).reshape(s[1:])
> 
> AssertionError: No edge has more than 2 cells. Are cells listed twice?

sounds like a self-intersection?

**Comment by rob-rb** [comment] 2021-02-09 22:09
I tried to spot who is changing the topology of my mesh: it happens calling mesh.flip_until_delaunay(). After the call there is an edge with 4-cells. Maybe it would be better to raise an error in such cases.

**Comment by nschloe** [comment] 2021-02-10 07:22
It's hard to debug these issues without being able to reproduce them. That's why it's
important to always attach an MWE, a _minimal working example_. This includes the code
you used to generate the issue and perhaps other data (a mesh file etc.). In most cases,
50 percent of the work is making the example _minimal_ such that only the essence of the
issue remains.

Can you try and produce that?

**Comment by rob-rb** [comment] 2021-02-10 07:49
it's gonna be hard work. i'll try

**Comment by rob-rb** [comment] 2021-02-17 07:08
```
import meshplex
import numpy as np
[surface.zip](https://github.com/nschloe/optimesh/files/5993856/surface.zip)


from meshplex import *

mesh = meshplex.reader.read("surface.obj")
print("1")
mesh.flip_until_delaunay()
print("done")
points = mesh.points
faces = list(mesh.cells["points"])
mesh = MeshTri(points, faces)
print("done")
mesh.flip_until_delaunay()
print("2")
```

**Comment by nschloe** [comment] 2021-02-19 17:10
For me, this gives
```
1
done
done
Traceback (most recent call last):
  File "/tmp/mm.py", line 14, in <module>
    mesh.flip_until_delaunay()
  File "/home/nschloe/rcs/meshplex/meshplex/mesh_tri.py", line 1097, in flip_until_delaunay
    if np.all(self.ce_ratios[~self.is_boundary_edge_local] > -0.5 * tol):
  File "/home/nschloe/rcs/meshplex/meshplex/mesh_tri.py", line 429, in is_boundary_edge_local
    self.create_edges()
  File "/home/nschloe/rcs/meshplex/meshplex/mesh_tri.py", line 480, in create_edges
    assert np.all(cts < 3), "No edge has more than 2 cells. Are cells listed twice?"
AssertionError: No edge has more than 2 cells. Are cells listed twice?
```

**Comment by rob-rb** [comment] 2021-02-19 19:20
yep for me too. 

and at the same time I expected  the following code

points = mesh.points
faces = list(mesh.cells["points"])
mesh = MeshTri(points, faces)

to be an identity operator.  But it is not (when i introduce a second mesh.flip_until_delaunay() after print("1") it works!).
Why?

**Comment by nschloe** [comment] 2021-02-20 09:44
> yep for me too.

It looks like cells are listed twice then. :) That's usually not what you want.

> ```python
> points = mesh.points
> faces = list(mesh.cells["points"])
> mesh = MeshTri(points, faces)
>```
> to be an identity operator. 

What exactly changes?

**Comment by rob-rb** [comment] 2021-02-20 16:04
No no the cells are unique:

I introduced this somewhat naive test:

`import meshplex
import numpy as np
from meshplex import *

mesh = meshplex.reader.read("surface.obj")
print("1")
mesh.flip_until_delaunay()
print("done")
points = mesh.points
faces0 = list(mesh.cells["points"])

from collections import defaultdict
def control_uniqueness(faces):
    ht = defaultdict(int)
    for f in faces:
        ht[tuple(f)] += 1

    for k, count in ht.items():
        if count>1:
            raise RuntimeError("face is doubled")
    print("faces are unique")
control_uniqueness(faces0)
mesh = MeshTri(points, faces0)
faces1 = list(mesh.cells["points"])

control_uniqueness(faces1)
n = len(faces0)
for j in range(n):
    if tuple(faces1[j])!= tuple(faces0[j]):
        raise RuntimeError("not equal")
    
mesh.flip_until_delaunay()
print("2")`

which has the output
```

1
done
faces are unique
faces are unique
109027 109027
done
Traceback (most recent call last):
  File "C:/bar/spherene/minimal_optimesh_fail/show_problem.py", line 33, in <module>
    mesh.flip_until_delaunay()
  File "C:\Anaconda\lib\site-packages\meshplex\mesh_tri.py", line 1140, in flip_until_delaunay
    if np.all(self.ce_ratios[~self.is_boundary_edge_local] > -0.5 * tol):
  File "C:\Anaconda\lib\site-packages\meshplex\mesh_tri.py", line 459, in is_boundary_edge_local
    self.create_edges()
  File "C:\Anaconda\lib\site-packages\meshplex\mesh_tri.py", line 510, in create_edges
    assert np.all(cts < 3), "No edge has more than 2 cells. Are cells listed twice?"
AssertionError: No edge has more than 2 cells. Are cells listed twice?
```

**Comment by nschloe** [comment] 2021-02-24 18:13
Note to self: Issue occurs with
```python
import meshplex

mesh = meshplex.reader.read("surface.obj")
mesh.flip_until_delaunay()

mesh.create_facets()  # err
```
After edge flipping, the cell
```
17888 17887 17105
```
is listed twice. Probably an edge flip bug then.

**Comment by rob-rb** [comment] 2021-02-24 18:54
ja stimmt ich hatte einen Fehler in control_uniqueness:
jetzt:
`def control_uniqueness(faces):
    ht = defaultdict(int)
    for f in faces:
        f = list(f)
        f.sort()
        if f[0]==f[1] or f[1]==f[2]:
            raise RuntimeError("?")
        ht[tuple(f)] += 1
    err = False
    for k, count in ht.items():
        if count > 1:
            err = True
            print("face doubled ",k)
            #raise RuntimeError("face is doubled")
    if not err:
        print("faces are unique")
`
kriege ich auch face doubled  (17105, 17887, 17888)

**Comment by nschloe** [comment] 2021-02-25 07:59
Smaller MWE:
```python
import meshplex
import numpy as np

cells = np.array(
    [
        [4, 5, 2],
        [5, 6, 2],
        [8, 7, 6],
        [6, 7, 2],
        [4, 2, 1],
        [1, 2, 0],
        [2, 7, 3],
        [0, 2, 3],
    ]
)
points = np.array(
    [
        [4.00540750e00, 8.41882994e00, 1.87847398e-01],
        [4.15720337e00, 8.14281236e00, 9.12266346e-10],
        [4.30002833e00, 8.57424769e00, 1.04310192e-02],
        [4.05235481e00, 8.89348539e00, 2.06854700e-01],
        [4.25687935e00, 8.41702649e00, -1.80354934e-10],
        [4.28647665e00, 8.56681008e00, -3.27591539e-10],
        [4.28974575e00, 8.58639357e00, -1.84739328e-10],
        [4.36607782e00, 9.03478181e00, 2.94211691e-02],
        [4.33143378e00, 9.01150991e00, 2.88600116e-10],
    ]
)

mesh = meshplex.MeshTri(points, cells)

mesh.flip_until_delaunay()
mesh.create_facets()
```
```
Traceback (most recent call last):
  File "/tmp/d.py", line 33, in <module>
    mesh.create_facets()
  File "/home/nschloe/rcs/meshplex/meshplex/base.py", line 490, in create_facets
    raise MeshplexError(msg)
meshplex.exceptions.MeshplexError: Found 1 facets with more than two neighboring cells. Something is not right. The following cells are equal:
[0 1]
```

**Comment by nschloe** [comment] 2021-02-26 16:28
The issue is fixed with https://github.com/nschloe/meshplex/pull/119. (Edge flips which would duplicate cells/edges aren't performed.)

**Comment by nschloe** [comment] 2021-03-02 10:03
I've now settled for a more consistent fix. The reality is that duplicate cells can happen when performing edge flips on manifold meshes. The data structures are consistent too, but when trying to reinstate the mesh from points and cells only, edge construction will fail. The fix is to call the new `remove_duplicate_cells()` before constructing edges.

**Closed** 2021-04-09 17:34 UTC
